development:
  server: "http://localhost:9292/faye"
  secret_token: "secret"
test:
  server: "http://localhost:9292/faye"
  secret_token: "secret"
production:
  server: "http://example.com/faye"
  secret_token: "89ff62ef6b38aa054a2ba9fafe48b43fc6f951b5a1f76aff7c8f113560ffe8ee"
  signature_expiration: 3600 # one hour
